package lesson6.db.dao;

import lesson6.db.model.Categories;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoriesMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        long countByExample(ProductsMapper.CategoriesExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int deleteByExample(ProductsMapper.CategoriesExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int insert(Categories record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int insertSelective(Categories record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        List<Categories> selectByExample(ProductsMapper.CategoriesExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        Categories selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int updateByExampleSelective(@Param("record") Categories record, @Param("example") ProductsMapper.CategoriesExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int updateByExample(@Param("record") Categories record, @Param("example") ProductsMapper.CategoriesExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int updateByPrimaryKeySelective(Categories record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table categories
         *
         * @mbg.generated Sat Feb 26 20:51:31 SAMT 2022
         */
        int updateByPrimaryKey(Categories record);

}

